---
- name: Copy Vault Agent Configuration
  template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Create Vault Data and Certs Directory
  file:
    state: directory
    path: "{{ vault_data_dir }}/tls"
    owner: vault
    group: vault

- name: Start Vault Service
  systemd:
    name: vault
    enabled: no
    state: stopped