---
- name: Copy Nomad Agent Configuration
  template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl

- name: Create Directory for Service Overrides
  file:
    state: directory
    path: /etc/systemd/system/nomad.service.d
    owner: nomad
    group: nomad

- name: Nomad Service Environment Variables
  when:
    - role == "server"
  copy:
    dest: /etc/systemd/system/nomad.service.d/override.conf
    content: |
      [Service]
      Environment="VAULT_TOKEN={{ nomad_vault_token }}"
    owner: root
    group: root

- name: Start Nomad Service
  systemd:
    name: nomad
    daemon_reload: yes
    enabled: yes
    state: started