---
- name: Install Vault
  apt:
    name: vault-enterprise
    state: latest
    update_cache: yes

- name: Create Vault Data Directory
  file:
    state: directory
    path: "{{ vault_data_dir }}"
    owner: vault
    group: vault

- name: Disable Vault Service
  systemd:
    name: vault
    enabled: no