---
- name: Install Consul
  apt:
    name: consul-enterprise
    state: latest
    update_cache: yes

- name: Create Consul Data Directory
  file:
    state: directory
    path: "{{ consul_data_dir }}"
    owner: consul
    group: consul

- name: Disable Consul Service
  systemd:
    name: consul
    enabled: no